export const BOX_SESSION_MAX_PARTICIPANTS = 30;
export const BOX_SESSION_MIN_PARTICIPANTS = 1;
export const BOX_SESSION_CLAN_COUNT = 2;
export const BOX_SESSION_MAX_MEMBERS_PER_CLAN = 15;
export const BOX_SESSION_POINTS_PER_MEMBER = 420;
export const BOX_SESSION_TASK_COUNT = 29;
