/**
 * Enum of item materials
 */
export enum Material {
  PUU = 'puu',
  POLYESTERI = 'polyesteri',
  ALUMIINI = 'alumiini',
  PUUVILLA = 'puuvilla',
  VILLA = 'villa',
  TEKONAHKA = 'tekonahka',
  NAHKA = 'nahka',
  LASI = 'lasi',
  KASVI = 'kasvi',
  MUOVI = 'muovi',
  METALLI = 'metalli',
  LAMINAATTI = 'laminaatti',
  PAPERI = 'paperi',
  KANGAS = 'kangas',
  VALO = 'valo',
  VAHA = 'vaha',
  ELEKTRONIIKKA = 'elektroniikka',
  LASTULEVY = 'lastulevy',
  POSLIINI = 'posliini',
  TERÄS = 'teräs',
  TEIPPI = 'teippi',
  SAVI = 'savi',
  MELAMIINI = 'melamiini',
  KALUSTELEVY = 'kalustelevy',
  MAALI = 'maali',
}
