#Remember to remove anonymous volumes regularly with "docker volume prune"

#TODO: add the proxy back, close db port

services:
#  api_dev:
#    build:
#      dockerfile: dev_api.Dockerfile
#    container_name: altzone_api_dev
#    command: npm run docker_dev
#    depends_on:
#      - db_dev
#    networks:
#      - backend
#      - db
#    volumes:
#      - ./:/app
#      - node_modules:/app/node_modules
#    environment:
#      - HOST=altzone_api_dev
#      - PORT=8080
#      - MONGO_USERNAME=rootUser
#      - MONGO_PASSWORD=superSecretPassword
#      - MONGO_HOST=altzone_db_dev
#      - MONGO_PORT=27017
#      - MONGO_DB_NAME=altzone_dev

  db_dev:
    image: mongo:4.2.24-bionic
    container_name: altzone_db_dev
    #command: mongod --quiet --logpath /dev/null #disable logs
    networks:
      - db
    volumes:
      - altzone_db_dev:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootUser
      - MONGO_INITDB_ROOT_PASSWORD=superSecretPassword
      - MONGO_INITDB_DATABASE=altzone_dev
    ports:
      - 27017:27017

  #Only for development (it allows run malicious JS code on DB)
  #Starts at 8081 port be default
  panel_dev:
    image: mongo-express:0.54.0
    container_name: altzone_panel_dev
    depends_on:
      - db_dev
    networks:
      - backend
      - db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootUser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=superSecretPassword
      - ME_CONFIG_MONGODB_SERVER=altzone_db_dev
      - ME_CONFIG_SITE_BASEURL=/panel/
      - ME_CONFIG_SITE_COOKIESECRET=cookieParserMiddlewareSecret
      - ME_CONFIG_SITE_SESSIONSECRET=secretForSessionIdCookie
      - ME_CONFIG_OPTIONS_EDITORTHEME=ayu-dark

#  proxy_dev:
#    image: nginx:1.23.4-bullseye
#    container_name: altzone_proxy_dev
#    depends_on:
#      - panel_dev
#      - api_dev
#    ports:
#      - 8080:80
#    networks:
#      - backend
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  backend:
    name: altzone_backend_dev
  db:
    name: altzone_db_dev

volumes:
  altzone_db_dev:
  node_modules: