#Remember to remove anonymous volumes regularly with "docker volume prune"

services:
  api:
    build:
      dockerfile: ./api.Dockerfile
    container_name: altzone_api
    command: npm run docker_dev
    depends_on:
      - db
      - proxy
    networks:
      - backend
      - db
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - HOST=altzone_api
      - PORT=8080
      - MONGO_USERNAME=rootUser
      - MONGO_PASSWORD=superSecretPassword
      - MONGO_HOST=altzone_db
      - MONGO_PORT=27017
      - MONGO_DB_NAME=altzone

  db:
    image: mongo:4.2.24-bionic
    container_name: altzone_db
    command: mongod --quiet --logpath /dev/null #disable logs
    networks:
      - db
    volumes:
      - altzone_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootUser
      - MONGO_INITDB_ROOT_PASSWORD=superSecretPassword
      - MONGO_INITDB_DATABASE=altzone

  #Only for development (it allows run malicious JS code on DB)
  #Starts at 8081 port be default
  panel:
    image: mongo-express:0.54.0
    container_name: altzone_panel
    depends_on:
      - db
      - proxy
    networks:
      - backend
      - db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootUser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=superSecretPassword
      - ME_CONFIG_MONGODB_SERVER=altzone_db
      - ME_CONFIG_SITE_BASEURL=/panel/
      - ME_CONFIG_SITE_COOKIESECRET=cookieParserMiddlewareSecret
      - ME_CONFIG_SITE_SESSIONSECRET=secretForSessionIdCookie
      - ME_CONFIG_OPTIONS_EDITORTHEME=ayu-dark

  proxy:
    image: nginx:1.23.4-bullseye
    container_name: altzone_proxy
    ports:
      - 8080:80
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  backend:
    name: altzone_backend
  db:
    name: altzone_db

volumes:
  altzone_db:
  node_modules: