#Remember to remove anonymous volumes regularly with "docker volume prune"

services:
  db_dev:
    image: mongo:4.2.24-bionic
    container_name: altzone_db_dev
    #command: mongod --quiet --logpath /dev/null #disable logs
    networks:
      - db
    volumes:
      - altzone_db_dev:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootUser
      - MONGO_INITDB_ROOT_PASSWORD=superSecretPassword
      - MONGO_INITDB_DATABASE=altzone_dev
    ports:
      - 27017:27017

  #Only for development (it allows run malicious JS code on DB)
  #Starts at 8081 port be default
  panel_dev:
    image: mongo-express:0.54.0
    container_name: altzone_panel_dev
    depends_on:
      - db_dev
    networks:
      - backend
      - db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootUser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=superSecretPassword
      - ME_CONFIG_MONGODB_SERVER=altzone_db_dev
      - ME_CONFIG_SITE_BASEURL=/panel/
      - ME_CONFIG_SITE_COOKIESECRET=cookieParserMiddlewareSecret
      - ME_CONFIG_SITE_SESSIONSECRET=secretForSessionIdCookie
      - ME_CONFIG_OPTIONS_EDITORTHEME=ayu-dark
    ports:
      - 8081:8081

  redis:
    image: redis:7.4-bookworm
    container_name: altzone_redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=mySecretPassword
      - REDIS_APPENDONLY=yes
      - REDIS_MAXMEMORY=256mb
      - REDIS_PORT=6379
      - REDIS_LOGLEVEL=notice
    volumes:
      - altzone_redis_dev:/data
    networks:
      - redis

  mosquitto_dev:
    image: eclipse-mosquitto:2.0
    container_name: altzone_mosquitto_dev
    ports:
      - 1883:1883
    networks:
      - backend
    volumes:
      - altzone_mosquitto_dev:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log

  proxy_dev:
    build:
      dockerfile: dev_nginx.Dockerfile
    container_name: altzone_proxy_dev
    depends_on:
      - panel_dev
    ports:
      - 80:80
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/local/nginx/public

networks:
  backend:
    name: altzone_backend_dev
  db:
    name: altzone_db_dev
  redis:
    name: altzone_redis_dev

volumes:
  altzone_db_dev:
  altzone_redis_dev:
  altzone_mosquitto_dev: