#Remember to remove anonymous volumes regularly with "docker volume prune"

services:
  db_dev:
    build:
      dockerfile: ./mongo.Dockerfile
    container_name: altzone_db_dev
    networks:
      - db
    volumes:
      - altzone_db_dev:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
    ports:
      - 27017:27017

  redis:
    image: redis:8.2-rc1-alpine
    container_name: altzone_redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=mySecretPassword
      - REDIS_APPENDONLY=yes
      - REDIS_MAXMEMORY=256mb
      - REDIS_PORT=6379
      - REDIS_LOGLEVEL=notice
    volumes:
      - altzone_redis_dev:/data
    networks:
      - redis

  mosquitto_dev:
    image: eclipse-mosquitto:2.0.22
    container_name: altzone_mosquitto_dev
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - backend
    volumes:
      - altzone_mosquitto_dev:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log

networks:
  backend:
    name: altzone_backend_dev
  db:
    name: altzone_db_dev
  redis:
    name: altzone_redis_dev

volumes:
  altzone_db_dev:
    name: altzone_db_dev
  altzone_redis_dev:
  altzone_mosquitto_dev: