#docker compose -f prod_docker-compose.yml up

services:
  api:
    build:
      dockerfile: prod_api.Dockerfile
    container_name: altzone_api
    depends_on:
      - db
    networks:
      - backend
      - db
    environment:
      - HOST=altzone_api
      - PORT=8080
      - MONGO_USERNAME=rootUser
      - MONGO_PASSWORD=superSecretPassword
      - MONGO_HOST=altzone_db
      - MONGO_PORT=27017
      - MONGO_DB_NAME=altzone

  site:
    image: leolab1337/altzone_web_pages:v2
    container_name: altzone_site
    networks:
      - backend
    restart: always
    environment:
      - NEXT_PUBLIC_API_LINK=http://altzone_api:8080/api
      - NEXT_PUBLIC_API_DOMAIN=altzone_api:8080/api
      - ANALYZE=false
      - PORT=3000
      - HOSTNAME=altzone_site

  db:
    image: mongo:4.2.24-bionic
    container_name: altzone_db
    command: mongod --quiet --logpath /dev/null #disable logs
    networks:
      - db
    volumes:
      - altzone_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootUser
      - MONGO_INITDB_ROOT_PASSWORD=superSecretPassword
      - MONGO_INITDB_DATABASE=altzone

  proxy:
    build:
      dockerfile: ./prod_nginx.Dockerfile
    container_name: altzone_proxy
    depends_on:
      - api
      - site
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    volumes:
      - ./prod_nginx.conf:/etc/nginx/nginx.conf
      - ./owncloud/files/owncloud/files/public:/usr/local/nginx/public:ro
      - ./owncloud/files/owncloud/files/webgl_build_brotli:/usr/local/nginx/game
      - ./letsencrypt:/etc/letsencrypt

  owncloud:
    image: owncloud/server:10
    container_name: owncloud
    restart: always
    environment:
      - OWNCLOUD_DOMAIN=owncloud
      - OWNCLOUD_TRUSTED_DOMAINS=owncloud

      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=owncloud
      - OWNCLOUD_ADMIN_PASSWORD=owncloud
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    networks:
      - owncloud
    ports:
      - 8080:8080
    volumes:
      - ./owncloud:/mnt/data

  mariadb:
    image: mariadb:11.2 # minimum required ownCloud version is 10.9
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MARIADB_AUTO_UPGRADE=1
    networks:
      - owncloud
    command: [ "--max-allowed-packet=128M", "--innodb-log-file-size=64M" ]
    volumes:
      - owncloud_mariadb:/var/lib/mysql

  redis:
    image: redis:7
    container_name: owncloud_redis
    restart: always
    networks:
      - owncloud
    command: [ "--databases", "1" ]
    volumes:
      - owncloud_redis:/data

networks:
  backend:
    name: altzone_backend
  db:
    name: altzone_db
  owncloud:
    name: altzone_owncloud

volumes:
  altzone_db:
  owncloud_mariadb:
  owncloud_redis: