#docker compose -f prod_docker-compose.yml up

services:
  api:
    build:
      dockerfile: prod_api.Dockerfile
    container_name: altzone_api
    depends_on:
      - db
    networks:
      - backend
      - db
      - owncloud
      - redis
    environment:
      - HOST=altzone_api
      - PORT=8080
      - MONGO_USERNAME=rootUser
      - MONGO_PASSWORD=superSecretPassword
      - MONGO_HOST=altzone_db
      - MONGO_PORT=27017
      - MONGO_DB_NAME=altzone
      - OWNCLOUD_HOST=owncloud
      - OWNCLOUD_PORT=8080
      - OWNCLOUD_USER=user
      - OWNCLOUD_PASSWORD=password
      - OWNCLOUD_LOG_FILES_ROOT=/log-files
      - REDIS_PASSWORD=mySecretPassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MOSQUITTO_HOST=mosquitto
      - MOSQUITTO_PORT=1883
      - MOSQUITTO_SUBSCRIBER_USER=subscriber
      - MOSQUITTO_SUBSCRIBER_PASSWORD=subscriberPassword
      - MOSQUITTO_PUBLISHER=publisher
      - MOSQUITTO_PUBLISHER_PASSWORD=publisherPassword
      
  site:
    image: leolab1337/altzone_web_pages:v2
    container_name: altzone_site
    networks:
      - backend
    restart: always
    environment:
      - NEXT_PUBLIC_API_LINK=http://altzone_api:8080
      - NEXT_PUBLIC_API_DOMAIN=altzone_api:8080
      - ANALYZE=false
      - PORT=3000
      - HOSTNAME=altzone_site

  site_dev:
    image: leolab1337/altzone_web_pages:v2
    container_name: altzone_site_dev
    networks:
      - backend
    restart: always
    environment:
      - NEXT_PUBLIC_API_LINK=http://altzone_api:8080
      - NEXT_PUBLIC_API_DOMAIN=altzone_api:8080
      - ANALYZE=false
      - PORT=3001
      - HOSTNAME=altzone_site

  swagger:
    image: deriabin/altzone:swagger1
    container_name: altzone_swagger
    depends_on:
      - api
    networks:
      - swagger
    ports:
      - 8081:8081
    environment:
      - PORT=8081

  db:
    image: mongo:4.2.24-bionic
    container_name: altzone_db
    command: mongod --quiet --logpath /dev/null #disable logs
    networks:
      - db
    volumes:
      - altzone_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootUser
      - MONGO_INITDB_ROOT_PASSWORD=superSecretPassword
      - MONGO_INITDB_DATABASE=altzone

  redis:
    image: redis:7.4-bookworm
    container_name: altzone_redis
    environment:
      - REDIS_PASSWORD=mySecretPassword
      - REDIS_APPENDONLY=yes
      - REDIS_MAXMEMORY=512mb
      - REDIS_PORT=6379
      - REDIS_LOGLEVEL=warning
    volumes:
      - altzone_redis:/data
    networks:
      - redis

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: altzone_mosquitto
    networks:
      - backend
    volumes:
      - altzone_mosquitto:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log

  owncloud:
    image: owncloud/server:10.15
    container_name: altzone_owncloud
    restart: always
    networks:
      - owncloud
      - owncloud_db
    ports:
      - 8082:8080
    depends_on:
      - owncloud_db
    volumes:
     - ./owncloud:/mnt/data
    environment:
      - OWNCLOUD_DOMAIN=owncloud
      - OWNCLOUD_TRUSTED_DOMAINS=owncloud,api,0.0.0.0,localhost
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=root
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=owncloud_db
      - OWNCLOUD_ADMIN_USERNAME=user
      - OWNCLOUD_ADMIN_PASSWORD=password
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=false

  owncloud_db:
    image: mariadb:11.1
    container_name: altzone_owncloud_db
    restart: always
    networks:
      - owncloud_db
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: owncloud
    volumes:
      - owncloud_db:/var/lib/mysql

  proxy:
    build:
      dockerfile: ./prod_nginx.Dockerfile
    container_name: altzone_proxy
    depends_on:
      - api
      - site
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
      - altzone_swagger
      - owncloud
    volumes:
      - ./prod_nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/local/nginx/public:ro
      - ./webgl_build_brotli:/usr/local/nginx/game
      - ./letsencrypt:/etc/letsencrypt

networks:
  backend:
    name: altzone_backend
  db:
    name: altzone_db
  redis:
    name: altzone_redis
  swagger:
    name: altzone_swagger
  owncloud:
    name: altzone_owncloud
  owncloud_db:
    name: altzone_owncloud_db

volumes:
  altzone_db:
  owncloud_db:
  altzone_redis:
  altzone_mosquitto: