#docker compose -f prod_docker-compose.yml up

services:
  api:
    build:
      dockerfile: prod_api.Dockerfile
    container_name: altzone_api
    depends_on:
      - db
    networks:
      - backend
      - db
    environment:
      - HOST=altzone_api
      - PORT=8080
      - MONGO_USERNAME=rootUser
      - MONGO_PASSWORD=superSecretPassword
      - MONGO_HOST=altzone_db
      - MONGO_PORT=27017
      - MONGO_DB_NAME=altzone

  site:
    image: leolab1337/altzone_web_pages:v1
    container_name: altzone_site
    networks:
      - backend
    restart: always
    environment:
      - NEXT_PUBLIC_API_LINK=http://altzone_api:8080/api
      - NEXT_PUBLIC_API_DOMAIN=altzone_api:8080/api
      - ANALYZE=false
      - PORT=3000
      - HOSTNAME=altzone_site

  db:
    image: mongo:4.2.24-bionic
    container_name: altzone_db
    command: mongod --quiet --logpath /dev/null #disable logs
    networks:
      - db
    volumes:
      - altzone_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootUser
      - MONGO_INITDB_ROOT_PASSWORD=superSecretPassword
      - MONGO_INITDB_DATABASE=altzone

  proxy:
    build:
      dockerfile: ./prod_nginx.Dockerfile
    container_name: altzone_proxy
    depends_on:
      - api
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    volumes:
      - ./prod_nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/local/nginx/public:ro
      - ./webgl_build_brotli:/usr/local/nginx/game
      - ./letsencrypt:/etc/letsencrypt

networks:
  backend:
    name: altzone_backend
  db:
    name: altzone_db

volumes:
  altzone_db: