#docker compose -f server_docker-compose.yml up

services:
  api:
    image: deriabin/altzone:api.1
    container_name: altzone_api
    depends_on:
      - db
    networks:
      - backend
      - db
    environment:
      - HOST=altzone_api
      - PORT=8080
      - MONGO_USERNAME=rootUser
      - MONGO_PASSWORD=superSecretPassword
      - MONGO_HOST=altzone_db
      - MONGO_PORT=27017
      - MONGO_DB_NAME=altzone

  db:
    image: mongo:4.2.24-bionic
    container_name: altzone_db
    command: mongod --quiet --logpath /dev/null #disable logs
    networks:
      - db
    volumes:
      - altzone_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootUser
      - MONGO_INITDB_ROOT_PASSWORD=superSecretPassword
      - MONGO_INITDB_DATABASE=altzone

  proxy:
    image: nginx:1.23.4-bullseye
    container_name: altzone_proxy
    depends_on:
      - api
    restart: always
    ports:
      - 80:80
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  backend:
    name: altzone_backend
  db:
    name: altzone_db

volumes:
  altzone_db:
