#docker compose -f sonar_docker-compose.yml up
# user: admin, password: admin

services:
  sonar:
    image: sonarqube:lts-community
    container_name: altzone_sonar
    depends_on:
      - sonar_db
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_temp:/opt/sonarqube/temp
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"

  sonar_db:
    image: postgres:17.2-bullseye
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_postgresql:/var/lib/postgresql
      - sonar_postgresql_data:/var/lib/postgresql/data

volumes:
  sonar_data:
  sonar_logs:
  sonar_extensions:
  sonar_temp:
  sonar_postgresql:
  sonar_postgresql_data:
