import { toContainSE } from './matchers/serviceError/array/toContainSE';
import { toContainSE_LESS_THAN_MIN } from './matchers/serviceError/array/toContainSE_LESS_THAN_MIN';
import { toContainSE_MISCONFIGURED } from './matchers/serviceError/array/toContainSE_MISCONFIGURED';
import { toContainSE_MORE_THAN_MAX } from './matchers/serviceError/array/toContainSE_MORE_THAN_MAX';
import { toContainSE_NOT_ALLOWED } from './matchers/serviceError/array/toContainSE_NOT_ALLOWED';
import { toContainSE_NOT_ARRAY } from './matchers/serviceError/array/toContainSE_NOT_ARRAY';
import { toContainSE_NOT_BOOLEAN } from './matchers/serviceError/array/toContainSE_NOT_BOOLEAN';
import { toContainSE_NOT_DATE } from './matchers/serviceError/array/toContainSE_NOT_DATE';
import { toContainSE_NOT_FOUND } from './matchers/serviceError/array/toContainSE_NOT_FOUND';
import { toContainSE_NOT_NUMBER } from './matchers/serviceError/array/toContainSE_NOT_NUMBER';
import { toContainSE_NOT_OBJECT } from './matchers/serviceError/array/toContainSE_NOT_OBJECT';
import { toContainSE_NOT_STRING } from './matchers/serviceError/array/toContainSE_NOT_STRING';
import { toContainSE_NOT_UNIQUE } from './matchers/serviceError/array/toContainSE_NOT_UNIQUE';
import { toContainSE_REQUIRED } from './matchers/serviceError/array/toContainSE_REQUIRED';
import { toContainSE_UNEXPECTED } from './matchers/serviceError/array/toContainSE_UNEXPECTED';
import { toContainSE_VALIDATION } from './matchers/serviceError/array/toContainSE_VALIDATION';
import { toContainSE_WRONG_ENUM } from './matchers/serviceError/array/toContainSE_WRONG_ENUM';
import { toEqualSE } from './matchers/serviceError/array/toEqualSE';
import { toBeSE } from './matchers/serviceError/individual/toBeSE';
import { toBeSE_LESS_THAN_MIN } from './matchers/serviceError/individual/toBeSE_LESS_THAN_MIN';
import { toBeSE_MISCONFIGURED } from './matchers/serviceError/individual/toBeSE_MISCONFIGURED';
import { toBeSE_MORE_THAN_MAX } from './matchers/serviceError/individual/toBeSE_MORE_THAN_MAX';
import { toBeSE_NOT_ALLOWED } from './matchers/serviceError/individual/toBeSE_NOT_ALLOWED';
import { toBeSE_NOT_ARRAY } from './matchers/serviceError/individual/toBeSE_NOT_ARRAY';
import { toBeSE_NOT_BOOLEAN } from './matchers/serviceError/individual/toBeSE_NOT_BOOLEAN';
import { toBeSE_NOT_DATE } from './matchers/serviceError/individual/toBeSE_NOT_DATE';
import { toBeSE_NOT_FOUND } from './matchers/serviceError/individual/toBeSE_NOT_FOUND';
import { toBeSE_NOT_NUMBER } from './matchers/serviceError/individual/toBeSE_NOT_NUMBER';
import { toBeSE_NOT_OBJECT } from './matchers/serviceError/individual/toBeSE_NOT_OBJECT';
import { toBeSE_NOT_STRING } from './matchers/serviceError/individual/toBeSE_NOT_STRING';
import { toBeSE_NOT_UNIQUE } from './matchers/serviceError/individual/toBeSE_NOT_UNIQUE';
import { toBeSE_REQUIRED } from './matchers/serviceError/individual/toBeSE_REQUIRED';
import { toBeSE_UNEXPECTED } from './matchers/serviceError/individual/toBeSE_UNEXPECTED';
import { toBeSE_VALIDATION } from './matchers/serviceError/individual/toBeSE_VALIDATION';
import { toBeSE_WRONG_ENUM } from './matchers/serviceError/individual/toBeSE_WRONG_ENUM';
import { toContainSE_NOT_AUTHORIZED } from './matchers/serviceError/array/toContainSE_NOT_AUTHORIZED';
import { toBeSE_NOT_AUTHORIZED } from './matchers/serviceError/individual/toBeSE_NOT_AUTHORIZED';

expect.extend({ toContainSE_LESS_THAN_MIN });
expect.extend({ toContainSE_MISCONFIGURED });
expect.extend({ toContainSE_MORE_THAN_MAX });
expect.extend({ toContainSE_NOT_ALLOWED });
expect.extend({ toContainSE_NOT_ARRAY });
expect.extend({ toContainSE_NOT_BOOLEAN });
expect.extend({ toContainSE_NOT_DATE });
expect.extend({ toContainSE_NOT_FOUND });
expect.extend({ toContainSE_NOT_NUMBER });
expect.extend({ toContainSE_NOT_OBJECT });
expect.extend({ toContainSE_NOT_STRING });
expect.extend({ toContainSE_NOT_UNIQUE });
expect.extend({ toContainSE_REQUIRED });
expect.extend({ toContainSE_UNEXPECTED });
expect.extend({ toContainSE_VALIDATION });
expect.extend({ toContainSE_WRONG_ENUM });
expect.extend({ toContainSE_NOT_AUTHORIZED });
expect.extend({ toContainSE });
expect.extend({ toEqualSE });

expect.extend({ toBeSE_LESS_THAN_MIN });
expect.extend({ toBeSE_MISCONFIGURED });
expect.extend({ toBeSE_MORE_THAN_MAX });
expect.extend({ toBeSE_NOT_ALLOWED });
expect.extend({ toBeSE_NOT_ARRAY });
expect.extend({ toBeSE_NOT_BOOLEAN });
expect.extend({ toBeSE_NOT_DATE });
expect.extend({ toBeSE_NOT_FOUND });
expect.extend({ toBeSE_NOT_NUMBER });
expect.extend({ toBeSE_NOT_OBJECT });
expect.extend({ toBeSE_NOT_STRING });
expect.extend({ toBeSE_NOT_UNIQUE });
expect.extend({ toBeSE_REQUIRED });
expect.extend({ toBeSE_UNEXPECTED });
expect.extend({ toBeSE_VALIDATION });
expect.extend({ toBeSE_WRONG_ENUM });
expect.extend({ toBeSE_NOT_AUTHORIZED });
expect.extend({ toBeSE });
