export enum MqttNotificationType {
  SONG_UPDATED = 'SONG_UPDATED',
  PLAYLIST_UPDATED = 'PLAYLIST_UPDATED',

  ROOM_UPDATED = 'ROOM_UPDATED',
  INVITE_RECEIVED = 'INVITE_RECEIVED',
  CLAN_INVITE_RECEIVED = 'CLAN_INVITE_RECEIVED',
  MATCH_FOUND = 'MATCH_FOUND',
  MATCH_STARTED = 'MATCH_STARTED',
  MATCH_FINISHED = 'MATCH_FINISHED',

  VOTING_CREATED = 'VOTING_CREATED',
  VOTING_UPDATED = 'VOTING_UPDATED',
  VOTING_ENDED = 'VOTING_ENDED',
  VOTING_ERROR = 'VOTING_ERROR',

  TASK_RECEIVED = 'TASK_RECEIVED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_ERROR = 'TASK_ERROR',
  CLAN_TASK_COMPLETED = 'CLAN_TASK_COMPLETED',
  MILESTONE_REACHED = 'MILESTONE_REACHED',
  DAILY_TASKS_RESET = 'DAILY_TASKS_RESET',

  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_LEFT = 'MEMBER_LEFT',

  FRIEND_REQUEST_CREATED = 'FRIEND_REQUEST_CREATED',
  FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REQUEST_REJECTED = 'FRIEND_REQUEST_REJECTED',

  INACTIVE_ROOMS_REMOVED = 'INACTIVE_ROOMS_REMOVED',
}
