import { Injectable } from "@nestjs/common";
import { InjectModel } from "@nestjs/mongoose";
import { Model } from "mongoose";
import {Box, publicReferences} from "./schemas/box.schema";
import BasicService from "../common/service/basicService/BasicService";
import {BoxReference} from "./enum/BoxReference.enum";
import {CreateBoxDto} from "./dto/createBox.dto";
import {IServiceReturn} from "../common/service/basicService/IService";
import {ObjectId} from "mongodb";

@Injectable()
export class BoxService {
    public constructor(
        @InjectModel(Box.name) public readonly model: Model<Box>,
    ){
        this.refsInModel = publicReferences;
        this.basicService = new BasicService(model);
    }

    public readonly refsInModel: BoxReference[];
    private readonly basicService: BasicService;

    /**
     * Initialize a box for testing session by creating a box, box admin profile and player,
     * chat, as well as 2 clans with soul homes, rooms and stocks.
     * Notice that if clan names are not provided they will be autogenerated: player name + clan + 1/2, i.e. "John clan 1"
     * Notice that if any errors occur on any of the initialization stage, all data of the box will be removed.
     * @param boxToInit box to create
     *
     * @returns created box and all corresponding data to it on success or ServiceErrors:
     *
     * - NOT_ALLOWED if the box for the provided admin already created
     * - NOT_UNIQUE if the provided player name or clan names already exist
     * - NOT_FOUND if the provided admin password does not exist
     * - REQUIRED if the provided input is null or undefined
     */
    public async initializeBox(boxToInit: CreateBoxDto): Promise<IServiceReturn<Box>> {
        return null;
    }

    /**
     * Creates a new box
     * @param box box to create
     * @returns created box on success or ServiceErrors:
     *
     * - REQUIRED if the provided input is null or undefined
     * - NOT_UNIQUE if a box with provided admin password already exists
     * - validation errors if input is invalid
     */
    public async createBox(box: Box): Promise<IServiceReturn<Box>> {
        return null;
    }

    /**
     * Removes all data associated with the box including:
     * - clans and their soul homes, rooms, stocks
     * - profiles and players
     * - chat
     * - daily tasks
     *
     * @param box_id
     */
    public async deleteBox(box_id: ObjectId | string): Promise<IServiceReturn<Box>> {
        return null;
    }

    /**
     * Checks whenever a box for specified group admin is already created.
     * @param groupAdminPassword group admin password
     *
     * @return true if the box is registered or false if not
     */
    private isBoxRegistered = async(groupAdminPassword: string): Promise<boolean> => {
        const [box, errors] = await this.basicService.readOne<Box>({ filter: { adminPassword: groupAdminPassword } });

        return box ? true : false;
    }
}
