services:
  # api:
  #   build:
  #     dockerfile: prod_api.Dockerfile
  #   container_name: altzone_api_dev
  #   depends_on:
  #     - db_dev
  #   networks:
  #     - backend
  #     - db
  #   environment:
  #     - HOST=altzone_api
  #     - PORT=8080
  #     - MONGO_USERNAME=rootUser
  #     - MONGO_PASSWORD=superSecretPassword
  #     - MONGO_HOST=altzone_db_dev
  #     - MONGO_PORT=27017
  #     - MONGO_DB_NAME=altzone_dev
  #     - OWNCLOUD_USER=
  #     - OWNCLOUD_PASSWORD=

  db_dev:
    image: mongo:4.2.24-bionic
    container_name: altzone_db_dev
    #command: mongod --quiet --logpath /dev/null #disable logs
    networks:
      - db
    volumes:
      - altzone_db_dev:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootUser
      - MONGO_INITDB_ROOT_PASSWORD=superSecretPassword
      - MONGO_INITDB_DATABASE=altzone_dev
    ports:
      - 27017:27017

  #Only for development (it allows run malicious JS code on DB)
  #Starts at 8081 port be default
  panel_dev:
    image: mongo-express:0.54.0
    container_name: altzone_panel_dev
    depends_on:
      - db_dev
    networks:
      - backend
      - db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootUser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=superSecretPassword
      - ME_CONFIG_MONGODB_SERVER=altzone_db_dev
      - ME_CONFIG_SITE_BASEURL=/panel/
      - ME_CONFIG_SITE_COOKIESECRET=cookieParserMiddlewareSecret
      - ME_CONFIG_SITE_SESSIONSECRET=secretForSessionIdCookie
      - ME_CONFIG_OPTIONS_EDITORTHEME=ayu-dark
    ports:
      - 8081:8081

  owncloud:
    image: owncloud:9
    container_name: altzone_owncloud
    restart: always
    networks:
      - owncloud
      - owncloud_db
    ports:
      - 8082:80
    depends_on:
      - owncloud_db
    volumes:
     - ./owncloud:/var/www/html

  owncloud_db:
    image: mariadb:11.1
    container_name: altzone_owncloud_db
    restart: always
    networks:
      - owncloud_db
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: owncloud
    volumes:
      - owncloud_db:/var/lib/mysql

  proxy_dev:
    build:
      dockerfile: dev_nginx.Dockerfile
    container_name: altzone_proxy_dev
    depends_on:
      - panel_dev
      - owncloud
      #- api
    ports:
      - 80:80
    networks:
      - backend
      - owncloud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/local/nginx/public

networks:
  backend:
    name: altzone_backend_dev
  db:
    name: altzone_db_dev
  owncloud:
    name: altzone_owncloud
  owncloud_db:
    name: altzone_owncloud_db

volumes:
  altzone_db_dev:
  node_modules:
  owncloud_db: