import { ItemName } from '../enum/itemName.enum';
import { Material } from '../enum/material.enum';
import { Rarity } from '../enum/rarity.enum';
import { Recycling } from '../enum/recycling.enum';

/**
 * Default properties of an Item
 */
export type ItemProperty = {
  name: ItemName;
  weight: number;
  furnitureSize: number[];
  price: number;
  rarity: Rarity;
  recycling: Recycling;
  isFurniture: boolean;
  material: Material[];
};

/**
 * Record of all defined Item properties
 */
export const itemProperties: Record<ItemName, ItemProperty> = {
  [ItemName.SOFA_TAAKKA]: {
    name: ItemName.SOFA_TAAKKA,
    weight: 30,
    furnitureSize: [7, 3, 4],
    price: 150,
    rarity: Rarity.rare,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.PUU, Material.POLYESTERI],
  },
  [ItemName.ARMCHAIR_TAAKKA]: {
    name: ItemName.ARMCHAIR_TAAKKA,
    weight: 16,
    furnitureSize: [3, 3, 4],
    price: 120,
    rarity: Rarity.rare,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.POLYESTERI, Material.PUU],
  },
  [ItemName.MIRROR_TAAKKA]: {
    name: ItemName.MIRROR_TAAKKA,
    weight: 8,
    furnitureSize: [2, 2, 4],
    price: 100,
    rarity: Rarity.common,
    recycling: Recycling.WOOD,
    isFurniture: false,
    material: [Material.LASI, Material.PUU],
  },
  [ItemName.FLOORLAMP_TAAKKA]: {
    name: ItemName.FLOORLAMP_TAAKKA,
    weight: 3,
    furnitureSize: [2, 2, 5],
    price: 240,
    rarity: Rarity.epic,
    recycling: Recycling.ELECTRICAL_EQUIPMENT,
    isFurniture: false,
    material: [Material.ALUMIINI],
  },
  [ItemName.COFFEETABLE_Taakka]: {
    name: ItemName.COFFEETABLE_Taakka,
    weight: 26,
    furnitureSize: [3, 2, 1],
    price: 80,
    rarity: Rarity.common,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.MELAMIINI, Material.KALUSTELEVY],
  },
  [ItemName.SIDETABLE_TAAKKA]: {
    name: ItemName.SIDETABLE_TAAKKA,
    weight: 16,
    furnitureSize: [2, 2, 2],
    price: 60,
    rarity: Rarity.common,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.MELAMIINI, Material.KALUSTELEVY],
  },
  [ItemName.CLOSET_TAAKKA]: {
    name: ItemName.CLOSET_TAAKKA,
    weight: 48,
    furnitureSize: [4, 2, 7],
    price: 120,
    rarity: Rarity.rare,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.PUU],
  },
  [ItemName.SINK_SCHRODINGER]: {
    name: ItemName.SINK_SCHRODINGER,
    weight: 13,
    furnitureSize: [3, 1, 3],
    price: 150,
    rarity: Rarity.rare,
    recycling: Recycling.LANDFILL,
    isFurniture: false,
    material: [Material.POSLIINI, Material.TERÄS],
  },
  [ItemName.TOILET_SCHRODINGER]: {
    name: ItemName.TOILET_SCHRODINGER,
    weight: 31,
    furnitureSize: [3, 1, 3],
    price: 150,
    rarity: Rarity.rare,
    recycling: Recycling.LANDFILL,
    isFurniture: false,
    material: [Material.POSLIINI],
  },
  [ItemName.MIRROR_SCHRODINGER]: {
    name: ItemName.MIRROR_SCHRODINGER,
    weight: 7,
    furnitureSize: [2, 0, 4],
    price: 150,
    rarity: Rarity.rare,
    recycling: Recycling.GLASS,
    isFurniture: false,
    material: [Material.LASI],
  },
  [ItemName.CARPET_SCHRODINGER]: {
    name: ItemName.CARPET_SCHRODINGER,
    weight: 6,
    furnitureSize: [8, 4, 0],
    price: 150,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.KANGAS, Material.MUOVI],
  },
  [ItemName.BATHTUB_SCHRODINGER]: {
    name: ItemName.BATHTUB_SCHRODINGER,
    weight: 50,
    furnitureSize: [4, 2, 2], // "korkeus" 2-3 in the sheet
    price: 1150,
    rarity: Rarity.epic,
    recycling: Recycling.LANDFILL,
    isFurniture: false,
    material: [Material.POSLIINI, Material.TERÄS],
  },
  [ItemName.SOFA_RAKKAUS]: {
    name: ItemName.SOFA_RAKKAUS,
    weight: 27,
    furnitureSize: [7, 3, 2],
    price: 130,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.POLYESTERI],
  },
  [ItemName.ARMCHAIR_RAKKAUS]: {
    name: ItemName.ARMCHAIR_RAKKAUS,
    weight: 13,
    furnitureSize: [3, 2, 3],
    price: 100,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.POLYESTERI],
  },
  [ItemName.CLOSET_RAKKAUS]: {
    name: ItemName.CLOSET_RAKKAUS,
    weight: 45,
    furnitureSize: [2, 1, 4],
    price: 130,
    rarity: Rarity.common,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.PUU],
  },
  [ItemName.CARPET_RAKKAUS]: {
    name: ItemName.CARPET_RAKKAUS,
    weight: 6,
    furnitureSize: [4, 2, 0],
    price: 100,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.KANGAS, Material.MUOVI],
  },
  [ItemName.COFFEETABLE_RAKKAUS]: {
    name: ItemName.COFFEETABLE_RAKKAUS,
    weight: 20,
    furnitureSize: [4, 2, 2],
    price: 60,
    rarity: Rarity.common,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.PUU],
  },
  [ItemName.DININGTABLE_RAKKAUS]: {
    name: ItemName.DININGTABLE_RAKKAUS,
    weight: 30,
    furnitureSize: [4, 2, 2],
    price: 100,
    rarity: Rarity.rare,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.PUU],
  },
  [ItemName.BED_RAKKAUS]: {
    name: ItemName.BED_RAKKAUS,
    weight: 20,
    furnitureSize: [6, 6, 3],
    price: 200,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.POLYESTERI],
  },
  [ItemName.MIRROR_RAKKAUS]: {
    name: ItemName.MIRROR_RAKKAUS,
    weight: 10,
    furnitureSize: [3, 0, 5],
    price: 170,
    rarity: Rarity.common,
    recycling: Recycling.GLASS,
    isFurniture: false,
    material: [Material.LASI, Material.METALLI],
  },
  [ItemName.CEILINGLAMP_RAKKAUS]: {
    name: ItemName.CEILINGLAMP_RAKKAUS,
    weight: 2,
    furnitureSize: [2, 2, 4],
    price: 200,
    rarity: Rarity.epic,
    recycling: Recycling.GLASS,
    isFurniture: false,
    material: [Material.LASI],
  },
  [ItemName.CHAIR_NEURO]: {
    name: ItemName.CHAIR_NEURO,
    weight: 10,
    furnitureSize: [3, 3, 4],
    price: 170,
    rarity: Rarity.epic,
    recycling: Recycling.ELECTRICAL_EQUIPMENT,
    isFurniture: true,
    material: [Material.ALUMIINI, Material.TEKONAHKA],
  },
  [ItemName.DRESSER_NEURO]: {
    name: ItemName.DRESSER_NEURO,
    weight: 24,
    furnitureSize: [4, 2, 3],
    price: 100,
    rarity: Rarity.rare,
    recycling: Recycling.ELECTRICAL_EQUIPMENT,
    isFurniture: true,
    material: [Material.LASTULEVY, Material.ALUMIINI],
  },
  [ItemName.STOOL_NEURO]: {
    name: ItemName.STOOL_NEURO,
    weight: 4,
    furnitureSize: [2, 2, 2],
    price: 40,
    rarity: Rarity.common,
    recycling: Recycling.ELECTRICAL_EQUIPMENT,
    isFurniture: true,
    material: [Material.ALUMIINI, Material.TEKONAHKA],
  },
  [ItemName.CLOCK_NEURO]: {
    name: ItemName.CLOCK_NEURO,
    weight: 1,
    furnitureSize: [2, 0, 4],
    price: 40,
    rarity: Rarity.common,
    recycling: Recycling.ELECTRICAL_EQUIPMENT,
    isFurniture: false,
    material: [Material.ALUMIINI, Material.ELEKTRONIIKKA],
  },
  [ItemName.CHAIR_POLARITY]: {
    name: ItemName.CHAIR_POLARITY,
    weight: 5,
    furnitureSize: [2, 3, 4],
    price: 60,
    rarity: Rarity.common,
    recycling: Recycling.METAL,
    isFurniture: true,
    material: [Material.ALUMIINI],
  },
  [ItemName.BOOKSHELF_POLARITY]: {
    name: ItemName.BOOKSHELF_POLARITY,
    weight: 40,
    furnitureSize: [3, 1, 6],
    price: 120,
    rarity: Rarity.rare,
    recycling: Recycling.METAL,
    isFurniture: true,
    material: [Material.ALUMIINI],
  },
  [ItemName.TABLE_POLARITY]: {
    name: ItemName.TABLE_POLARITY,
    weight: 10,
    furnitureSize: [4, 4, 2],
    price: 80,
    rarity: Rarity.common,
    recycling: Recycling.METAL,
    isFurniture: true,
    material: [Material.ALUMIINI],
  },
  [ItemName.COMMODE_MUISTOJA]: {
    name: ItemName.COMMODE_MUISTOJA,
    weight: 17,
    furnitureSize: [3, 2, 3],
    price: 100,
    rarity: Rarity.rare,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.PUU, Material.PAPERI, Material.KANGAS],
  },
  [ItemName.PICTURES_MUISTOJA]: {
    name: ItemName.PICTURES_MUISTOJA,
    weight: 2,
    furnitureSize: [4, 0, 3],
    price: 60,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.PUU],
  },
  [ItemName.SOFA_MUISTOJA]: {
    name: ItemName.SOFA_MUISTOJA,
    weight: 20,
    furnitureSize: [6, 2, 3],
    price: 100,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.TEKONAHKA],
  },
  [ItemName.ARMCHAIR_MUISTOJA]: {
    name: ItemName.ARMCHAIR_MUISTOJA,
    weight: 5,
    furnitureSize: [3, 2, 4],
    price: 60,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.TEKONAHKA],
  },
  [ItemName.COFFEETABLE_MUISTOJA]: {
    name: ItemName.COFFEETABLE_MUISTOJA,
    weight: 20,
    furnitureSize: [4, 2, 3],
    price: 60,
    rarity: Rarity.common,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.PUU, Material.PAPERI],
  },
  [ItemName.DRAWINGS_MUISTOJA]: {
    name: ItemName.DRAWINGS_MUISTOJA,
    weight: 1,
    furnitureSize: [3, 0, 2],
    price: 60,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.PAPERI, Material.TEIPPI],
  },
  [ItemName.FICUS_MUISTOJA]: {
    name: ItemName.FICUS_MUISTOJA,
    weight: 3,
    furnitureSize: [4, 2, 7],
    price: 120,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.KASVI, Material.MUOVI, Material.SAVI],
  },
  [ItemName.FLOWERS_MUISTOJA]: {
    name: ItemName.FLOWERS_MUISTOJA,
    weight: 1,
    furnitureSize: [2, 2, 3],
    price: 50,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.KASVI, Material.MUOVI, Material.LASI],
  },
  [ItemName.CARPET_MUISTOJA]: {
    name: ItemName.CARPET_MUISTOJA,
    weight: 7,
    furnitureSize: [8, 5, 0],
    price: 150,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.KANGAS],
  },
  [ItemName.WINDOW_MUISTOJA]: {
    name: ItemName.WINDOW_MUISTOJA,
    weight: 1,
    furnitureSize: [3, 0, 4],
    price: 50,
    rarity: Rarity.common,
    recycling: Recycling.GLASS,
    isFurniture: false,
    material: [Material.LASI, Material.KANGAS],
  },
  [ItemName.PAINTING_MUISTOJA]: {
    name: ItemName.PAINTING_MUISTOJA,
    weight: 2,
    furnitureSize: [3, 0, 4],
    price: 40,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.PUU, Material.MAALI],
  },
  [ItemName.TOYFOX_MUISTOJA]: {
    name: ItemName.TOYFOX_MUISTOJA,
    weight: 1,
    furnitureSize: [2, 2, 2],
    price: 70,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.KANGAS],
  },
  [ItemName.SOFA_UNI]: {
    name: ItemName.SOFA_UNI,
    weight: 15,
    furnitureSize: [6, 3, 5],
    price: 130,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.ALUMIINI, Material.PUUVILLA, Material.VILLA],
  },
  [ItemName.BED_UNI]: {
    name: ItemName.BED_UNI,
    weight: 30,
    furnitureSize: [6, 7, 5],
    price: 200,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [
      Material.ALUMIINI,
      Material.PUUVILLA,
      Material.VILLA,
      Material.ELEKTRONIIKKA,
    ],
  },
  [ItemName.CLOSET_UNI]: {
    name: ItemName.CLOSET_UNI,
    weight: 40,
    furnitureSize: [5, 3, 7],
    price: 240,
    rarity: Rarity.epic,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [
      Material.PUU,
      Material.VILLA,
      Material.METALLI,
      Material.ELEKTRONIIKKA,
    ],
  },
  [ItemName.HOLOGRAM_KYLMATULEVAISUUS]: {
    name: ItemName.HOLOGRAM_KYLMATULEVAISUUS,
    weight: 0,
    furnitureSize: [4, 1, 2],
    price: 200,
    rarity: Rarity.epic,
    recycling: undefined,
    isFurniture: false,
    material: [Material.VALO],
  },
  [ItemName.SOFA_KYLMATULEVAISUUS]: {
    name: ItemName.SOFA_KYLMATULEVAISUUS,
    weight: 35,
    furnitureSize: [6, 2, 3],
    price: 150,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.TEKONAHKA],
  },
  [ItemName.TABLE_KYLMATULEVAISUUS]: {
    name: ItemName.TABLE_KYLMATULEVAISUUS,
    weight: 10,
    furnitureSize: [1, 1, 1],
    price: 30,
    rarity: Rarity.common,
    recycling: Recycling.METAL,
    isFurniture: true,
    material: [Material.METALLI, Material.LASI],
  },
  [ItemName.CLOSET_KIPU]: {
    name: ItemName.CLOSET_KIPU,
    weight: 50,
    furnitureSize: [4, 3, 6],
    price: 150,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.NAHKA],
  },
  [ItemName.SOFA_KIPU]: {
    name: ItemName.SOFA_KIPU,
    weight: 80,
    furnitureSize: [6, 3, 3],
    price: 125,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.NAHKA],
  },
  [ItemName.CHAIR_KIPU]: {
    name: ItemName.CHAIR_KIPU,
    weight: 15,
    furnitureSize: [2, 3, 4],
    price: 65,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.NAHKA],
  },
  [ItemName.TABLE_KIPU]: {
    name: ItemName.TABLE_KIPU,
    weight: 28,
    furnitureSize: [3, 2, 2],
    price: 50,
    rarity: Rarity.common,
    recycling: undefined,   // undefined in the sheet
    isFurniture: true,
    material: [Material.PUU, Material.NAHKA],
  },
  [ItemName.PLANT_KIPU]: {
    name: ItemName.PLANT_KIPU,
    weight: 1.5,
    furnitureSize: [1, 1, 2],
    price: 25,
    rarity: Rarity.common,
    recycling: undefined, // "biojäte" in the sheet
    isFurniture: false,
    material: [Material.KASVI],
  },
  [ItemName.SOFA_KIUSAAMINEN]: {
    name: ItemName.SOFA_KIUSAAMINEN,
    weight: 35,
    furnitureSize: [7, 3, 3],
    price: 130,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.KALUSTELEVY, Material.PUU, Material.POLYESTERI],
  },
  [ItemName.WINDOW_KIUSAAMINEN]: {
    name: ItemName.WINDOW_KIUSAAMINEN,
    weight: 50,
    furnitureSize: [3, 0, 4],
    price: 288,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.PUU, Material.LASI],
  },
  [ItemName.SOFA_STRESS]: {
    name: ItemName.SOFA_STRESS,
    weight: 40,
    furnitureSize: [5, 4, 4],
    price: 160,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [
      Material.POLYESTERI,
      Material.PUU,
      Material.PAPERI,
      Material.NAHKA,
      Material.METALLI,
      Material.KANGAS,
    ],
  },
  [ItemName.CHAIR_STRESS]: {
    name: ItemName.CHAIR_STRESS,
    weight: 15,
    furnitureSize: [3, 3, 3],
    price: 60,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.PAPERI, Material.MUOVI, Material.NAHKA],
  },
  [ItemName.BED_STRESS]: {
    name: ItemName.BED_STRESS,
    weight: 80,
    furnitureSize: [4, 2, 5],
    price: 120,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [
      Material.PUU,
      Material.KANGAS,
      Material.PAPERI,
      Material.MUOVI,
      Material.POLYESTERI,
      Material.METALLI,
    ],
  },
  [ItemName.FLOORLAMP_STRESS]: {
    name: ItemName.FLOORLAMP_STRESS,
    weight: 10,
    furnitureSize: [3, 3, 5],
    price: 100,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [
      Material.MUOVI,
      Material.PAPERI,
      Material.POLYESTERI,
      Material.METALLI,
    ],
  },
  [ItemName.FLOORSHELF_STRESS]: {
    name: ItemName.FLOORSHELF_STRESS,
    weight: 35,
    furnitureSize: [2, 3, 2],
    price: 90,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.MUOVI, Material.METALLI, Material.PAPERI],
  },
  [ItemName.GARBAGEBIN_STRESS]: {
    name: ItemName.GARBAGEBIN_STRESS,
    weight: 5,
    furnitureSize: [2, 2, 2],
    price: 20,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.MUOVI, Material.PAPERI],
  },
  [ItemName.TABLE_STRESS]: {
    name: ItemName.TABLE_STRESS,
    weight: 50,
    furnitureSize: [4, 2, 3],
    price: 80,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [
      Material.MUOVI,
      Material.PAPERI,
      Material.METALLI,
      Material.ALUMIINI,
    ],
  },
  [ItemName.COFFEETABLE_OCD]: {
    name: ItemName.COFFEETABLE_OCD,
    weight: 30,
    furnitureSize: [4, 3, 4],
    price: 80,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [],
  },
  [ItemName.OVEN_OCD]: {
    name: ItemName.OVEN_OCD,
    weight: 60,
    furnitureSize: undefined,
    price: 80,
    rarity: Rarity.common,
    recycling: Recycling.ELECTRICAL_EQUIPMENT,
    isFurniture: true,
    material: [Material.METALLI],
  },
  [ItemName.SINK_OCD]: {
    name: ItemName.SINK_OCD,
    weight: 30,
    furnitureSize: [2, 2, 3],
    price: 100,
    rarity: Rarity.common,
    recycling: undefined,
    isFurniture: false,
    material: [Material.POSLIINI, Material.TERÄS],
  },
  [ItemName.SOFA_OCD]: {
    name: ItemName.SOFA_OCD,
    weight: 120,
    furnitureSize: [8, 3, 4],
    price: 150,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.POLYESTERI],
  },
  [ItemName.DESK_OCD]: {
    name: ItemName.DESK_OCD,
    weight: 80,
    furnitureSize: [4, 2, 5],
    price: 120,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.METALLI, Material.PUU, Material.MUOVI],
  },
  [ItemName.FLOORLAMP_OCD]: {
    name: ItemName.FLOORLAMP_OCD,
    weight: 10,
    furnitureSize: [4, undefined, 5], // "Syvyys ruuduissa" undefined in the sheet
    price: 50,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.MUOVI, Material.METALLI],
  },
  [ItemName.TOILET_OCD]: {
    name: ItemName.TOILET_OCD,
    weight: 30,
    furnitureSize: [3, 2, 3],
    price: 100,
    rarity: Rarity.common,
    recycling: undefined,
    isFurniture: false,
    material: [Material.POSLIINI, Material.TERÄS],
  },
  [ItemName.FLOWER_GUILTYPLEASURE]: {
    name: ItemName.FLOWER_GUILTYPLEASURE,
    weight: 3,
    furnitureSize: [2, 2, 3],
    price: 100,
    rarity: Rarity.common,
    recycling: Recycling.METAL,
    isFurniture: false,
    material: [Material.TERÄS, Material.KASVI],
  },
  [ItemName.CARPET_GUILTYPLEASURE]: {
    name: ItemName.CARPET_GUILTYPLEASURE,
    weight: 11,
    furnitureSize: [4, 2, 0],
    price: 500,
    rarity: Rarity.rare,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.KANGAS],
  },
  [ItemName.LAMP_GUILTYPLEASURE]: {
    name: ItemName.LAMP_GUILTYPLEASURE,
    weight: 3,
    furnitureSize: [2, 1, 3],
    price: 150,
    rarity: Rarity.rare,
    recycling: Recycling.ELECTRICAL_EQUIPMENT,
    isFurniture: false,
    material: [Material.TERÄS, Material.ALUMIINI, Material.ELEKTRONIIKKA],
  },
  [ItemName.BED_DELIRIUM]: {
    name: ItemName.BED_DELIRIUM,
    weight: 40,
    furnitureSize: [5, 7, 5],
    price: 170,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.POLYESTERI, Material.PUUVILLA],
  },
  [ItemName.CARPET_DELIRIUM]: {
    name: ItemName.CARPET_DELIRIUM,
    weight: 6,
    furnitureSize: [9, 7, 3],
    price: 90,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.PUUVILLA],
  },
  [ItemName.ROCKINGCHAIR]: {
    name: ItemName.ROCKINGCHAIR,
    weight: 15,
    furnitureSize: [3, 4, 3],
    price: 75,
    rarity: Rarity.common,
    recycling: Recycling.WOOD,
    isFurniture: true,
    material: [Material.PUU],
  },
  [ItemName.WALLCLOCK_DELIRIUM]: {
    name: ItemName.WALLCLOCK_DELIRIUM,
    weight: 1,
    furnitureSize: [2, 2, 2],
    price: 10,
    rarity: Rarity.common,
    recycling: Recycling.ELECTRICAL_EQUIPMENT,
    isFurniture: false,
    material: [Material.ALUMIINI, Material.ELEKTRONIIKKA],
  },
  [ItemName.WINDOW_DELIRIUM]: {
    name: ItemName.WINDOW_DELIRIUM,
    weight: 10,
    furnitureSize: [4, 4, 3],
    price: 40,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.PUU, Material.LASI, Material.KANGAS, Material.METALLI],
  },
  [ItemName.SOFA_DELIRIUM]: {
    name: ItemName.SOFA_DELIRIUM,
    weight: 120,
    furnitureSize: [7, 4, 5],
    price: 120,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.POLYESTERI],
  },
  [ItemName.WARDROBE_DELIRIUM]: {
    name: ItemName.WARDROBE_DELIRIUM,
    weight: 50,
    furnitureSize: [4, 3, 7],
    price: 80,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.MUOVI, Material.METALLI],
  },
  [ItemName.ROCKINGCHAIR_FEAROFDEATH]: {
    name: ItemName.ROCKINGCHAIR_FEAROFDEATH,
    weight: 15,
    furnitureSize: [3, 3, 4],
    price: 80,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU],
  },
  [ItemName.BED_FEAROFDEATH]: {
    name: ItemName.BED_FEAROFDEATH,
    weight: 60,
    furnitureSize: [5, 7, 4],
    price: 100,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.METALLI, Material.KANGAS, Material.MUOVI],
  },
  [ItemName.CANDELABRA_FEAROFDEATH]: {
    name: ItemName.CANDELABRA_FEAROFDEATH,
    weight: 10,
    furnitureSize: [2, 2, 4],
    price: 40,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.METALLI, Material.VAHA],
  },
  [ItemName.WALLCLOCK_FEAROFDEATH]: {
    name: ItemName.WALLCLOCK_FEAROFDEATH,
    weight: 2,
    furnitureSize: [1, 2, 1],
    price: 40,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU],
  },
  [ItemName.MAKEUPTABLE_FEAROFDEATH]: {
    name: ItemName.MAKEUPTABLE_FEAROFDEATH,
    weight: 60,
    furnitureSize: [5, 5, 5],
    price: 80,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [
      Material.METALLI,
      Material.MUOVI,
      Material.LASI,
      Material.PUU,
      Material.VAHA,
    ],
  },
  [ItemName.DRAWER_FEAROFDEATH]: {
    name: ItemName.DRAWER_FEAROFDEATH,
    weight: 60,
    furnitureSize: [3, 3, 4],
    price: 70,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.METALLI, Material.MUOVI, Material.PAPERI],
  },
  [ItemName.WARDROBE_FEAROFDEATH]: {
    name: ItemName.WARDROBE_FEAROFDEATH,
    weight: 90,
    furnitureSize: [5, 3, 7],
    price: 50,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.METALLI],
  },
  [ItemName.BED_NOSTALGIA]: {
    name: ItemName.BED_NOSTALGIA,
    weight: 70,
    furnitureSize: [4, 6, 7],
    price: 100,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [
      Material.PUU,
      Material.METALLI,
      Material.POLYESTERI,
      Material.KANGAS,
      Material.PUUVILLA,
    ],
  },
  [ItemName.SHELVING_NOSTALGIA]: {
    name: ItemName.SHELVING_NOSTALGIA,
    weight: 30,
    furnitureSize: [5, 4, 6],
    price: 70,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.MUOVI, Material.KANGAS],
  },
  [ItemName.TOYCARS_NOSTALGIA]: {
    name: ItemName.TOYCARS_NOSTALGIA,
    weight: 1,
    furnitureSize: [3, 3, 2],
    price: 20,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.MUOVI, Material.MAALI],
  },
  [ItemName.CARPET_NOSTALGIA]: {
    name: ItemName.CARPET_NOSTALGIA,
    weight: 5,
    furnitureSize: [6, 4, 4],
    price: 50,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.PUUVILLA],
  },
  [ItemName.DOLLHOUSE_NOSTALGIA]: {
    name: ItemName.DOLLHOUSE_NOSTALGIA,
    weight: 1,
    furnitureSize: [2, 2, 2],
    price: 30,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.MUOVI, Material.PUU, Material.METALLI, Material.KANGAS],
  },
  [ItemName.DRAWINGS_NOSTALGIA]: {
    name: ItemName.DRAWINGS_NOSTALGIA,
    weight: 0.1,
    furnitureSize: [3, 2, 3],
    price: 10,
    rarity: Rarity.common,
    recycling: undefined,   // undefined in the sheet
    isFurniture: false,
    material: [Material.PAPERI],
  },
  [ItemName.STICKERS_NOSTALGIA]: {
    name: ItemName.STICKERS_NOSTALGIA,
    weight: 0.1,
    furnitureSize: [3, 2, 3],
    price: 20,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.MUOVI, Material.TEIPPI],
  },
  [ItemName.TABLE_NOSTALGIA]: {
    name: ItemName.TABLE_NOSTALGIA,
    weight: 60,
    furnitureSize: [4, 4, 3],
    price: 70,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.MUOVI, Material.PAPERI],
  },
  [ItemName.WINDOW_NOSTALGIA]: {
    name: ItemName.WINDOW_NOSTALGIA,
    weight: 10,
    furnitureSize: [5, 3, 5],
    price: 30,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.LASI, Material.PUU, Material.KANGAS, Material.METALLI],
  },
  [ItemName.BED_NYKTOPHOBIA]: {
    name: ItemName.BED_NYKTOPHOBIA,
    weight: 50,
    furnitureSize: [5, 7, 4],
    price: 70,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [Material.PUU, Material.KANGAS, Material.VILLA],
  },
  [ItemName.CLOTHESRACK_NYKTOPHOBIA]: {
    name: ItemName.CLOTHESRACK_NYKTOPHOBIA,
    weight: 7,
    furnitureSize: [5, 3, 6],
    price: 20,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [
      Material.METALLI,
      Material.KANGAS,
      Material.VILLA,
      Material.MUOVI,
    ],
  },
  [ItemName.WORKTABLE_NYKTOPHOBIA]: {
    name: ItemName.WORKTABLE_NYKTOPHOBIA,
    weight: 50,
    furnitureSize: [5, 5, 5],
    price: 80,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: true,
    material: [
      Material.METALLI,
      Material.PUU,
      Material.MUOVI,
      Material.ELEKTRONIIKKA,
      Material.LASI,
      Material.KANGAS,
    ],
  },
  [ItemName.DOOR_NYKTOPHOBIA]: {
    name: ItemName.DOOR_NYKTOPHOBIA,
    weight: 3,
    furnitureSize: [3, 2, 4],
    price: 5,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.PUU, Material.METALLI],
  },
  [ItemName.LAMP_NYKTOPHOBIA]: {
    name: ItemName.LAMP_NYKTOPHOBIA,
    weight: 6,
    furnitureSize: undefined,
    price: 30,
    rarity: Rarity.common,
    recycling: Recycling.METAL,
    isFurniture: false,
    material: [Material.METALLI, Material.LASI],
  },
  [ItemName.WINDOW_NYKTOPHOBIA]: {
    name: ItemName.WINDOW_NYKTOPHOBIA,
    weight: 5,
    furnitureSize: [3, 2, 6],
    price: 5,
    rarity: Rarity.common,
    recycling: Recycling.MIXED_WASTE,
    isFurniture: false,
    material: [Material.LASI, Material.METALLI],
  },
};
