name: Enforce Branch Naming Convention

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch name: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ ^(feature|docs|bug|change|test)/[a-z0-9]+(-[a-z0-9]+)*-[0-9]+$ ]]; then
            echo "✅ Branch name is valid"
            exit 0
          else
            echo "❌ Branch name must follow: <prefix>/<description>-<number> with no double dashes"
            exit 1
          fi
