name: Print ProjectV2 IDs

on:
  workflow_dispatch:

jobs:
  print-project-ids:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read

    steps:
      - name: Print your org Projects (v2)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Fetching Projects..."
          curl -s -H "Authorization: bearer $GH_TOKEN" \
               -H "Content-Type: application/json" \
               -d '{"query":"query { organization(login: \"Alt-Org\") { projectsV2(first: 10) { nodes { id title } } } }"}' \
               https://api.github.com/graphql

      - name: Print fields for one project (replace PROJECT_ID)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Fetching fields from selected project..."
          curl -s -H "Authorization: bearer $GH_TOKEN" \
               -H "Content-Type: application/json" \
               -d '{"query":"query { node(id: \"YOUR_PROJECT_ID\") { ... on ProjectV2 { title fields(first: 20) { nodes { id name dataType ... on ProjectV2SingleSelectField { options { id name } } } } } }"}' \
               https://api.github.com/graphql
