name: Print ProjectV2 Info

on:
  workflow_dispatch:  # allows manual run from the Actions tab

jobs:
  fetch-project-info:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_PROJECTS_PAT }}  # Your Personal Access Token goes here

    steps:
      - name: Fetch Projects (v2) from organization
        run: |
          echo "🔍 Fetching Projects for your organization..."

          curl -s -H "Authorization: bearer $GH_TOKEN" \
               -H "Content-Type: application/json" \
               -X POST https://api.github.com/graphql \
               -d '{"query":"query { organization(login: \"Alt-Org\") { projectsV2(first: 10) { nodes { id title } } } }"}'

      - name: Fetch fields and options from a specific Project
        run: |
          echo "🔍 Fetching fields and options for selected Project..."

          curl -s -H "Authorization: bearer $GH_TOKEN" \
               -H "Content-Type: application/json" \
               -X POST https://api.github.com/graphql \
               -d '{"query":"query { node(id: \"YOUR_PROJECT_ID\") { ... on ProjectV2 { title fields(first: 20) { nodes { id name dataType ... on ProjectV2SingleSelectField { options { id name } } } } } }"}'
