name: Add PR basic info
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  automate-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Automate labels, assignees, and issue linking
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const branch = pr.head.ref;
            const prNumber = pr.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const author = pr.user.login;

            // Add "PR" label
            let labelsToAdd = ["PR"];

            // Extract prefix label
            const prefixMatch = branch.match(/^(feature|docs|bug|change|test)\//);
            if (prefixMatch) {
              labelsToAdd.push(prefixMatch[1]);
            }

            // Apply labels
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: labelsToAdd
            });

            // Assign PR to the author
            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number: prNumber,
              assignees: [author]
            });

            // Extract issue number from end of branch name
            const issueMatch = branch.match(/-(\d+)$/);
            if (issueMatch) {
              const issueNumber = issueMatch[1];

              // Insert "Closes #issue" into PR body if not already present
              const closesPhrase = `Closes #${issueNumber}`;
              if (!pr.body || !pr.body.includes(closesPhrase)) {
                const updatedBody = (pr.body || "") + `\n\n${closesPhrase}`;
                await github.rest.pulls.update({
                  owner,
                  repo,
                  pull_number: prNumber,
                  body: updatedBody
                });
              }
            }
